version: "3"
services:
  redis4proxypool:
    image: redis:alpine
    container_name: redis4proxypool
    volumes:
      - ./data:/data

  proxypool:
    build: .
    container_name: proxypool
    depends_on:
      - redis4proxypool
    ports:
      - "5555:5555"
    restart: always
    environment:
      PROXYPOOL_REDIS_HOST: redis4proxypool
    volumes:
      - .:/app
    command: ["supervisord", "-c", "supervisord.conf"]